### ISSUE TITLE
[SDK Request] Java SDK

### ISSUE THREAD

**Issue by rhamzeh** [openfga/sdk-generator#70]
Related Roadmap issue: https://github.com/openfga/roadmap/issues/5
Related Discussion: https://github.com/orgs/openfga/discussions/31

**Comment by rorychatterton** [comment]
I am working on a Kotlin SDK in #86  which should also work for Java.

**Comment by booniepepper** [comment]
I'd like to suggest we make a Java SDK before considering a Kotlin SDK for the following reasons:

1. Java has an interoperability story for many other JVM languages. Kotlin, Scala, Groovy, Clojure, for example can all interoperate with Java objects.
   * Kotlin has a less-favorable story here, for example Kotlin objects cannot easily be extended by a Scala object due to conflicts on methods objects inherit from both systems (`===` is an example). Kotlin and Groovy closures can also have a weird relationship.
* Java releases language versions less often, and is more extreme in avoiding breaking changes. Code written and compiled with Java 1 will still be compatible (compile-time and run-time) with code written and compiled with Java 21, for example. This is not the case with Kotlin, which can require alignment of the version of Kotlin compiler used by both vendors and consumers. This means it'll be cheaper in terms of dependency updating (even if it's just compilers) for OpenFGA to invest in Java than in Kotlin.
2. It's comparatively easy to build a thin Kotlin client over a Java core client and deliver both a minimal idiomatic Java experience and an idiomatic Kotlin experience. If Java calls into Kotlin it will need to have Kotlin classes coming from (at least) a Kotlin standard library dependency that it otherwise shouldn't require.
